apiVersion: apps/v1
kind: Deployment
metadata:
  name: speeddeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speed
      version: "3.0"
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: speed
        version: "3.0"
    spec:
      containers:
        - name: speedcontainer
          image: saipavangockerhub/speeddcrk8s:3.0
          ports:
            - name: tomcatport
              containerPort: 8080
              protocol: TCP
#RollingUpdate


