apiVersion: apps/v1
kind: Deployment
metadata:
  name: speeddeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speed
      version: "1.0"
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: speed
      version: "1.0"
  template:
    metadata:S
      labels:
        app: speed
        version: "1.0"
    spec:
      containers:
        - name: speedcontainer
          image: saipavangockerhub/speeddcrk8s:1.0
          ports:
            - name: tomcatport
              containerPort: 8080
              protocol: TCP
# If you want to check application healthy you can use
# readinessProbe
#LivnessProve
#If you want to specfy resource declaratio
#Resourcedeclaration
